#!/usr/bin/env bash

set -e

tags=${BUILD_TAGS:--tags debug}
appver=${VERSION:-0.0.1}

export CGO_ENABLED=0

go clean   ./...
go build   ${tags} -ldflags "-X main.appVersion=${appver}"  ./cmd/authsvc-cli
go build   ${tags} -ldflags "-X main.appVersion=${appver}"  ./cmd/authserver
go build   ${tags} -ldflags "-X main.appVersion=${appver}"  ./cmd/userserver
