#!/usr/bin/env bash

#
# Put ourselves at the known project root location, and go back where
# we were on exit.
#
PROJECT_ROOT="$(git rev-parse --show-toplevel)"
function _trap_exit() {
  popd &> /dev/null
}
trap _trap_exit EXIT
pushd "${PROJECT_ROOT}" &> /dev/null

#
# Source environment overrides if present
#
if [ -f ".local.config" ]; then
  source ".local.config"
fi

set -e

./api serve
